# -*- coding: utf-8 -*-
"""RESULTS P1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OcUm8wCRltmFC8ZKjVw4skgo-WqJevFD
"""

!unzip "A4.2 Archivos de Apoyo - 06-02-26.zip"

!ls

!find /content -type d | grep -i p1

# Commented out IPython magic to ensure Python compatibility.
# %cd "A4.2 Archivos de Apoyo - 06-02-26"
!ls

!ls P1
!ls P2
!ls P3

"""
Cálculo de estadísticas poblacionales POR ARCHIVO.
"""

import os
import math
import time


CARPETA_DATOS = "P1"
PALABRAS_EXCLUIDAS = ("result", "answer", "solution", "output")


def archivo_valido(nombre):
    nombre = nombre.lower()
    return nombre.endswith(".txt") and not any(p in nombre for p in PALABRAS_EXCLUIDAS)


def leer_archivo(ruta):
    datos = []
    with open(ruta, "r", encoding="utf-8") as file:
        for linea in file:
            try:
                datos.append(float(linea.strip()))
            except ValueError:
                pass
    return datos


def media(datos):
    return sum(datos) / len(datos)


def mediana(datos):
    ordenados = sorted(datos)
    mitad = len(ordenados) // 2
    if len(ordenados) % 2 == 0:
        return (ordenados[mitad - 1] + ordenados[mitad]) / 2
    return ordenados[mitad]


def moda(datos):
    frecuencia = {}
    for valor in datos:
        frecuencia[valor] = frecuencia.get(valor, 0) + 1
    max_frec = max(frecuencia.values())
    return [k for k, v in frecuencia.items() if v == max_frec]


def varianza_poblacional(datos, promedio):
    return sum((x - promedio) ** 2 for x in datos) / len(datos)


def desviacion_poblacional(varianza):
    return math.sqrt(varianza)


def procesar_archivo(nombre):
    inicio = time.time()
    ruta = os.path.join(CARPETA_DATOS, nombre)
    datos = leer_archivo(ruta)

    promedio = media(datos)
    varianza = varianza_poblacional(datos, promedio)
    desviacion = desviacion_poblacional(varianza)

    resultado = (
        f"Archivo: {nombre}\n"
        f"Media: {promedio}\n"
        f"Mediana: {mediana(datos)}\n"
        f"Moda: {moda(datos)}\n"
        f"Varianza poblacional: {varianza}\n"
        f"Desviación estándar poblacional: {desviacion}\n"
        f"Tiempo: {time.time() - inicio} segundos\n"
    )

    os.makedirs("../results", exist_ok=True)
    salida = f"../results/Statistics_{nombre.replace('.txt', '')}.txt"

    with open(salida, "w", encoding="utf-8") as file:
        file.write(resultado)

    print(resultado)


def main():
    for archivo in os.listdir(CARPETA_DATOS):
        if archivo_valido(archivo):
            procesar_archivo(archivo)


if __name__ == "__main__":
    main()