# -*- coding: utf-8 -*-
"""RESULTS P3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_7cy7MvlYEiS-jfxtf65eFhDcdeB1wb4
"""

!unzip "A4.2 Archivos de Apoyo - 06-02-26.zip"

!ls

!find /content -type d | grep -i p1

# Commented out IPython magic to ensure Python compatibility.
# %cd "A4.2 Archivos de Apoyo - 06-02-26"
!ls

!ls P1
!ls P2
!ls P3

"""
Conteo de palabras POR ARCHIVO.
"""

import os
import time


CARPETA_DATOS = "P3"
PALABRAS_EXCLUIDAS = ("result", "answer", "solution", "output")


def archivo_valido(nombre):
    nombre = nombre.lower()
    return nombre.endswith(".txt") and not any(p in nombre for p in PALABRAS_EXCLUIDAS)


def limpiar_palabra(palabra):
    palabra = palabra.strip().lower()
    return palabra if palabra else "(blank)"


def procesar_archivo(nombre):
    inicio = time.time()
    ruta = os.path.join(CARPETA_DATOS, nombre)

    conteo = {}
    total = 0

    with open(ruta, "r", encoding="utf-8") as file:
        for linea in file:
            palabra = limpiar_palabra(linea)
            conteo[palabra] = conteo.get(palabra, 0) + 1
            total += 1

    resultado = (
        f"Archivo: {nombre}\n\n"
        "Row Labels\tCount of TC1\n"
    )

    for palabra in sorted(conteo):
        resultado += f"{palabra}\t{conteo[palabra]}\n"

    resultado += f"Grand Total\t{total}\n"
    resultado += f"\nTiempo: {time.time() - inicio} segundos\n"

    os.makedirs("../results", exist_ok=True)
    salida = f"../results/WordCount_{nombre.replace('.txt', '')}.txt"

    with open(salida, "w", encoding="utf-8") as file:
        file.write(resultado)

    print(resultado)


def main():
    for archivo in os.listdir(CARPETA_DATOS):
        if archivo_valido(archivo):
            procesar_archivo(archivo)


if __name__ == "__main__":
    main()