# -*- coding: utf-8 -*-
"""RESULTS P2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PVPkpPYNLKGFnMRchDhrHUhG1AjjUcQ2
"""

!unzip "A4.2 Archivos de Apoyo - 06-02-26.zip"

!ls

!find /content -type d | grep -i p1

# Commented out IPython magic to ensure Python compatibility.
# %cd "A4.2 Archivos de Apoyo - 06-02-26"
!ls

!ls P1
!ls P2
!ls P3

"""
Conversión de números decimales a binario y hexadecimal POR ARCHIVO.
"""

import os
import time


CARPETA_DATOS = "P2"
PALABRAS_EXCLUIDAS = ("result", "answer", "solution", "output")


def archivo_valido(nombre):
    nombre = nombre.lower()
    return nombre.endswith(".txt") and not any(p in nombre for p in PALABRAS_EXCLUIDAS)


def decimal_a_binario(numero):
    if numero == 0:
        return "0"

    negativo = numero < 0
    numero = abs(numero)
    binario = ""

    while numero > 0:
        binario = str(numero % 2) + binario
        numero //= 2

    if negativo:
        binario = "1" + binario

    return binario


def decimal_a_hexadecimal(numero):
    if numero == 0:
        return "0"

    digitos = "0123456789ABCDEF"
    negativo = numero < 0
    numero = abs(numero)
    hexadecimal = ""

    while numero > 0:
        hexadecimal = digitos[numero % 16] + hexadecimal
        numero //= 16

    if negativo:
        hexadecimal = "FFFFFFFF" + hexadecimal

    return hexadecimal


def procesar_archivo(nombre):
    inicio = time.time()
    ruta = os.path.join(CARPETA_DATOS, nombre)

    filas = []
    item = 1

    with open(ruta, "r", encoding="utf-8") as file:
        for linea in file:
            linea = linea.strip()

            try:
                numero = int(linea)
                binario = decimal_a_binario(numero)
                hexadecimal = decimal_a_hexadecimal(numero)

                filas.append(
                    f"{item}\t{numero}\t{binario}\t{hexadecimal}"
                )

            except ValueError:
                print(f"Error en archivo {nombre}, línea {item}: {linea}")
                filas.append(
                    f"{item}\t{linea}\t#VALUE!\t#VALUE!"
                )

            item += 1

    resultado = (
        f"Archivo: {nombre}\n"
        "ITEM\tDECIMAL\tBIN\tHEX\n"
        + "\n".join(filas)
        + f"\nTiempo: {time.time() - inicio} segundos\n"
    )

    os.makedirs("../results", exist_ok=True)
    salida = f"../results/Conversion_{nombre.replace('.txt', '')}.txt"

    with open(salida, "w", encoding="utf-8") as file:
        file.write(resultado)

    print(resultado)


def main():
    for archivo in os.listdir(CARPETA_DATOS):
        if archivo_valido(archivo):
            procesar_archivo(archivo)


if __name__ == "__main__":
    main()